export enum ElementType {
  Button = 'button',
  Checkboxes = 'checkboxes',
  DatePicker = 'datepicker',
  TimePicker = 'timepicker',
  Image = 'image',
  Overflow = 'overflow',
  TextInput = 'plain_text_input',
  RadioButtons = 'radio_buttons',
  StaticSelect = 'static_select',
  ExternalSelect = 'external_select',
  UserSelect = 'users_select',
  ConversationSelect = 'conversations_select',
  ChannelSelect = 'channels_select',
  StaticMultiSelect = 'multi_static_select',
  ExternalMultiSelect = 'multi_external_select',
  UserMultiSelect = 'multi_users_select',
  ConversationsMultiSelect = 'multi_conversations_select',
  ChannelsMultiSelect = 'multi_channels_select',
  URLInput = 'url_text_input',
  EmailInput = 'email_text_input',
  NumberInput = 'number_input',
}
